export JDBC_URL="jdbc:sqlserver://dalek4.icl.gtri.org:1433;databaseName=pacer;user=icl\paceradmin;password=cubes-9Ku33rZ"
export JDBC_USERNAME="icl\paceradmin"
export JDBC_PASSWORD="cubes-9Ku33rZ"
export JDBC_DRIVER="com.microsoft.sqlserver.jdbc.SQLServerDriver"
export HIBERNATE_DIALECT="org.hibernate.dialect.SQLServer2012Dialect"
export PACER_INDEX_SERVICE="https://gt-apps.hdap.gatech.edu/pacer-index-api/1.0.0/search"
export LOCAL_BULKDATA_PATH="/Users/mc142/Documents/workspace/ECR/temp"
export LOCAL_PACER_SECURITY="Basic username:password"
export LOCAL_PACER_URL="http://musctest.hdap.gatech.edu:8082/JobManagementSystem/List"
